// src/components/ui/Button.vue
<template>
  <button
    class="inline-flex items-center justify-center rounded-200 px-4 py-2 btn-text transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-secondary-400 disabled:opacity-50"
    :class="variantClasses"
    v-bind="$attrs"
  ><slot /></button>
</template>

<script setup lang="ts">
import { computed } from 'vue'
const props = withDefaults(defineProps<{ variant?: 'primary'|'secondary'|'ghost'|'white' }>(),{ variant:'primary' })
const variantClasses = computed(() => ({
  'bg-primary-500 text-white hover:bg-primary-600 active:shadow-pressed-primary': props.variant==='primary',
  'bg-secondary-500 text-white hover:bg-secondary-600': props.variant==='secondary',
  'bg-white text-primary-600 border border-primary-200 hover:bg-primary-50': props.variant==='white',
  'bg-transparent text-primary-600 hover:bg-primary-100': props.variant==='ghost',
}))
</script>

// components/ui/Button.tsx
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'
import { ButtonHTMLAttributes, forwardRef } from 'react'

const buttonVariants = cva(
    'inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-background',
    {
        variants: {
            variant: {
                default: 'bg-primary text-white hover:bg-primary/90',
                secondary: 'bg-muted text-foreground hover:bg-muted/80',
                outline: 'border border-input hover:bg-accent hover:text-accent-foreground',
                ghost: 'hover:bg-accent hover:text-accent-foreground',
                link: 'underline-offset-4 hover:underline text-primary',
                destructive: 'bg-destructive text-white hover:bg-destructive/90'
            },
            size: {
                default: 'h-10 py-2 px-4',
                sm: 'h-9 px-3 rounded-md',
                lg: 'h-11 px-8 rounded-md',
                icon: 'h-10 w-10'
            }
        },
        defaultVariants: {
            variant: 'default',
            size: 'default'
        }
    }
)

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement>, VariantProps<typeof buttonVariants> {}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(({ className, variant, size, ...props }, ref) => {
    return (
        <button ref={ref} className={cn(buttonVariants({ variant, size, className }))} {...props} />
    )
})

Button.displayName = 'Button'

export { Button, buttonVariants }
